// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knvrrwesxppwldomarhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudnJyd2VzeHBwd2xkb21hcmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODYwNDcsImV4cCI6MjA2MDQ2MjA0N30.urixVe3BXuH0K_oC1_0HfpqvDdW9AOn2gFuakaKof70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);